# Generated by Django 6.0.2 on 2026-03-01 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("groq", "Groq"),
                            ("openai", "OpenAI"),
                            ("gemini", "Google Gemini"),
                            ("openrouter", "OpenRouter"),
                        ],
                        max_length=50,
                    ),
                ),
                ("api_key_encrypted", models.TextField()),
                ("base_url", models.URLField(blank=True, null=True)),
                (
                    "default_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="providers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "provider")},
            },
        ),
    ]
