# Generated by Django 6.0.2 on 2026-03-16 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmprovider",
            name="provider",
            field=models.CharField(
                choices=[
                    ("groq", "Groq"),
                    ("anthropic", "Anthropic (Claude)"),
                    ("openai", "OpenAI"),
                    ("gemini", "Google Gemini"),
                    ("deepseek", "DeepSeek"),
                    ("grok", "Grok (xAI)"),
                    ("sarvam", "Sarvam AI"),
                    ("openrouter", "OpenRouter"),
                    ("custom", "Custom (BYOK URL)"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="SMTPServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nickname for this SMTP config", max_length=100
                    ),
                ),
                ("host", models.CharField(max_length=255)),
                ("port", models.IntegerField(default=587)),
                ("username", models.CharField(max_length=255)),
                ("password_encrypted", models.TextField()),
                ("use_tls", models.BooleanField(default=True)),
                ("from_name", models.CharField(max_length=255)),
                ("from_email", models.EmailField(max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smtp_servers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
