# Generated by Django 6.0.2 on 2026-03-16 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="response",
            new_name="notes",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="audience",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="min_quote",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="service",
        ),
        migrations.AddField(
            model_name="campaign",
            name="auto_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="campaign",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="sender_mode",
            field=models.CharField(
                choices=[
                    ("brand", "Brand (Official)"),
                    ("anonymous", "Anonymous (Stealth)"),
                ],
                default="brand",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="score",
            field=models.CharField(default="C", max_length=2),
        ),
        migrations.AddField(
            model_name="lead",
            name="social_links",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="lead",
            name="tech_stack",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="lead",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("enriched", "Enriched"),
                    ("audited", "Audited"),
                    ("drafted", "Draft Ready"),
                    ("emailed", "Emailed"),
                    ("replied", "Replied"),
                    ("converted", "Converted"),
                    ("lost", "Lost"),
                ],
                default="new",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="LeadDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("hook", models.TextField(blank=True, null=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("brand", "Brand"), ("anonymous", "Anonymous")],
                        max_length=20,
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to="campaigns.lead",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="FollowUp",
        ),
    ]
