# Generated by Django 6.0.2 on 2026-03-16 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaigns",
            "0002_rename_response_lead_notes_remove_campaign_audience_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignWorkflowStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_order", models.IntegerField(default=1)),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("ice_breaker", "Ice Breaker"),
                            ("audit", "Audit"),
                            ("follow_up", "Follow Up"),
                            ("custom", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                ("instructions", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_steps",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["step_order"],
                "unique_together": {("campaign", "step_order")},
            },
        ),
    ]
